name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PATH: /usr/local/opt/sphinx-doc/bin:/usr/local/opt/qt@5/bin:$PATH

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install -y \
              python3-dev python3-sphinx \
              qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5svg5-dev
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install qt@5 python@3.8 sphinx-doc
      - name: Build documentation
        run: make -C docs html
      - run: qmake
      - run: make
      - run: tests/tests
